export function apiUrl(concourseUrl: any): string;
export function skyTokenUrl(concourseUrl: any): string;
export function skyIssuerTokenUrl(concourseUrl: any): string;
export function infoUrl(apiUrl: any): string;
export function allTeamsUrl(apiUrl: any): string;
export function allWorkersUrl(apiUrl: any): string;
export function allPipelinesUrl(apiUrl: any): string;
export function allJobsUrl(apiUrl: any): string;
export function allBuildsUrl(apiUrl: any): string;
export function allResourcesUrl(apiUrl: any): string;
export function workerPruneUrl(apiUrl: any, workerName: any): string;
export function buildUrl(apiUrl: any, buildId: any): string;
export function buildResourcesUrl(apiUrl: any, buildId: any): string;
export function teamAuthTokenUrl(apiUrl: any, teamName: any): string;
export function teamUrl(apiUrl: any, teamName: any): string;
export function teamRenameUrl(apiUrl: any, teamName: any): string;
export function teamPipelinesUrl(apiUrl: any, teamName: any): string;
export function teamPipelineUrl(apiUrl: any, teamName: any, pipelineName: any): string;
export function teamPipelinePauseUrl(apiUrl: any, teamName: any, pipelineName: any): string;
export function teamPipelineUnpauseUrl(apiUrl: any, teamName: any, pipelineName: any): string;
export function teamPipelineRenameUrl(apiUrl: any, teamName: any, pipelineName: any): string;
export function teamPipelineConfigUrl(apiUrl: any, teamName: any, pipelineName: any): string;
export function teamBuildsUrl(apiUrl: any, teamName: any): string;
export function teamContainersUrl(apiUrl: any, teamName: any): string;
export function teamContainerUrl(apiUrl: any, teamName: any, containerId: any): string;
export function teamVolumesUrl(apiUrl: any, teamName: any): string;
export function teamPipelineBuildsUrl(apiUrl: any, teamName: any, pipelineName: any): string;
export function teamPipelineJobsUrl(apiUrl: any, teamName: any, pipelineName: any): string;
export function teamPipelineJobUrl(apiUrl: any, teamName: any, pipelineName: any, jobName: any): string;
export function teamPipelineJobPauseUrl(apiUrl: any, teamName: any, pipelineName: any, jobName: any): string;
export function teamPipelineJobUnpauseUrl(apiUrl: any, teamName: any, pipelineName: any, jobName: any): string;
export function teamPipelineJobBuildsUrl(apiUrl: any, teamName: any, pipelineName: any, jobName: any): string;
export function teamPipelineJobBuildUrl(apiUrl: any, teamName: any, pipelineName: any, jobName: any, buildName: any): string;
export function teamPipelineJobInputsUrl(apiUrl: any, teamName: any, pipelineName: any, jobName: any): string;
export function teamPipelineResourcesUrl(apiUrl: any, teamName: any, pipelineName: any): string;
export function teamPipelineResourceUrl(apiUrl: any, teamName: any, pipelineName: any, resourceName: any): string;
export function teamPipelineResourcePauseUrl(apiUrl: any, teamName: any, pipelineName: any, resourceName: any): string;
export function teamPipelineResourceUnpauseUrl(apiUrl: any, teamName: any, pipelineName: any, resourceName: any): string;
export function teamPipelineResourceTypesUrl(apiUrl: any, teamName: any, pipelineName: any): string;
export function teamPipelineResourceVersionsUrl(apiUrl: any, teamName: any, pipelineName: any, resourceName: any): string;
export function teamPipelineResourceVersionUrl(apiUrl: any, teamName: any, pipelineName: any, resourceName: any, versionId: any): string;
export function teamPipelineResourceVersionCausalityUrl(apiUrl: any, teamName: any, pipelineName: any, resourceName: any, versionId: any): string;
export function teamPipelineResourceVersionInputToUrl(apiUrl: any, teamName: any, pipelineName: any, resourceName: any, versionId: any): string;
export function teamPipelineResourceVersionOutputOfUrl(apiUrl: any, teamName: any, pipelineName: any, resourceName: any, versionId: any): string;
